#375 add fontist for required font installation
metanorma/metanorma-standoc pull request #377
Opened 2020-11-21 14:59 UTC by CAMOBAP

- #375

2020-11-24 02:27 UTC, ronaldtse commented on lib/asciidoctor/standoc/converter.rb
> +          Metanorma::Util.log("[fontinst] The font `#{font}` is not yet supported.", :info)
"fontist" not "fontinst"

2020-11-24 02:27 UTC, ronaldtse commented on lib/asciidoctor/standoc/converter.rb
> +          Metanorma::Util.log("[fontinst] Error: License acceptance required to install a necessary font." \
also, "fontist" not "fontinst"

2020-11-24 02:34 UTC, ronaldtse requested changes

2020-11-24 02:34 UTC, ronaldtse commented on lib/asciidoctor/standoc/converter.rb
> +          Metanorma::Util.log("[fontinst] Skip font installation process", :debug)
"fontist" not "fontinst"

2020-11-24 02:34 UTC, ronaldtse commented on lib/asciidoctor/standoc/converter.rb
> +          Metanorma::Util.log("[fontinst] Skip font installation process", :debug)
Please output the reason why font installation is skipped. e.g. 
* "Skipping installation of fonts -- no extra fonts to be installed for this flavor."
* "Skipping installation of fonts -- `no_install_fonts` option enabled"

2020-11-24 02:34 UTC, ronaldtse commented on lib/asciidoctor/standoc/converter.rb
> +          Metanorma::Util.log("[fontinst] Error: License acceptance required to install a necessary font." \
* "`confirm_license` option missing. You must accept font licenses to install fonts."
* "`continue_without_fonts` option enabled. Processing will continue without fonts installed".
* If `confirm_license` is not set and `continue_without_fonts` not set: "Aborting without proper fonts installed".

2020-11-24 02:34 UTC, ronaldtse commented on lib/asciidoctor/standoc/converter.rb
> +            "Accept required licenses with: `metanorma setup --agree-to-terms`.", log_type)
This is good.

2020-11-24 02:34 UTC, ronaldtse commented on lib/asciidoctor/standoc/converter.rb
> +          Metanorma::Util.log("[fontinst] The font `#{font}` is not yet supported.", :info)
Maybe add "Please file an issue at github.com/metanorma/metanorma-{flavor} to report this issue."?

2020-11-24 04:34 UTC, opoudjis approved these changes
Nice, and I see you reused my existing inheritance hook. Merge from master btw to update the relaton VCR cache, which is why rake is currently failing.

2020-11-24 17:59 UTC, CAMOBAP commented
@ronaldtse could you please review again

2020-11-25 02:44 UTC, ronaldtse approved these changes

2020-11-26 11:00 UTC, merged